- homeworks/pavel-didenko/06-js-basics-1/task6.js
Solved all the tasks except №16. The 16th makes my brain melt.
> [Homework #6] - JS-Part 1 by Pavel Didenko

- homeworks/pavel-didenko/07-js-basics-2/task7.js
- yarn.lock
Solved everything except the last one (sudoku puzzle).
> [Homework #7] - JS-Part 2 by Pavel Didenko

- homeworks/maia-stulicfontan/06-js-basics-1/scripts.js
* Adds JS file with solved Codewars tasks
> [Homework #6] - JS-Basics-1 by Maia Stulic Fontan

- homeworks/pavel-didenko/08-js-advanced-1/task8.js
- yarn.lock
Solved all tasks except 8th. I'll be honest, even though I could have copied it from somewhere, I don't understand the principle of modifying of an instance of the Object in such a way.
> [Homework #8] - JS-Advanced 1 by Pavel Didenko

- homeworks/maia-stulicfontan/07-js-basics-2/scripts.js
* Adds JS files with Codewars tasks (except Optional 3 and 4 items)
> [Homework #7] - JS-Basics-2 by Maia Stulic Fontan

- homeworks/oleg-gorodenskyi/08-js-advanced-1/script.js
Hi. Would be thankful, if you check my homework.
@ilya-ischenko
> [Homework #8] - JS Advanced 1 by Oleg Gorodenskyi

- homeworks/oleg-gorodenskyi/06-js-basics-1/codeWars.js
- yarn.lock
Hi. Changed the name of the branch and checked last changes.
@ilya-ischenko
> [Homework #6] - JS Basics 1 by Oleg Gorodenskyi

- homeworks/maia-stulicfontan/08-js-advanced-1/scripts.js
* Adds JS file with tasks for homework 8
> [Homework #8] - JS-Advanced-1 by Maia Stulic Fontan

- homeworks/andrew-kondratiyk/07-js-basics-2/index.js
Hello, I added solutions to all the katas, some of which I had solved before, so I left them as they were or slightly modified them.
> [Homework #7] - JS-Part-2 by Andrew Kondratiyk

- homeworks/pavel-didenko/09-js-advanced-2/task9.js
I think I implemented all what is needed, except the point
> non-valid / non-expected content of serialized line must call for an exception in case of waking up``
Don't know what scenarios does it have to handle. I understand that a person can add something to a serialized object, or remove something from it, but have no idea of how to spot it and throw exception.
> [Homework #9] - JS Advanced 2 By Pavel Didenko

- homeworks/ilya-petrenko/ip-07-js-basics-2/index.js
> [Homework #7] - JS-Part 2 by Ilya Petrenko

- homeworks/maia-stulicfontan/09-js-advanced-2/scripts.js
> [Homework #9] - JS-Advanced-2 by Maia Stulic Fontan

- homeworks/antonina-vechorko/06-js-basics-1/index.js
@solvd-mmelnyk please check homework. Thank you.
> [Homework #6] - JS-Basics-1 by Antonina Vechorko

- homeworks/yuri-pantsialei/07-js-basics-2/index.js
done all katas except the last one(optional)
> [Homework #7] - JS-Basics-2 by Yuri Pantelei

- homeworks/ilya-petrenko/ip-08-js-advanced-1/index.js
> [Homework #8] - JS Advanced 1 by Ilya Petrenko

- homeworks/antonina-vechorko/07-js-basics-2/index.js
@solvd-mmelnyk kindly check the homework #7. Thank you, will wait for your feedback!
> [Homework #7] - JS-Basics-2 by Antonina Vechorko

- homeworks/oleg-gorodenskyi/10-js-advanced-3/script.js
- homeworks/oleg-gorodenskyi/10-js-advanced-3/task 5/index.html
- homeworks/oleg-gorodenskyi/10-js-advanced-3/task 5/index.js
- homeworks/oleg-gorodenskyi/10-js-advanced-3/task 5/style.css
Deleted the previuos branch due to wrong name.
Renamed the branch and formatted the code.
@ilya-ischenko
> [Homework #10] - JS Advanced 3 By Oleg Gorodenskyi

- homeworks/anastasia-kladova/07-js-basics-2/script.js
- homeworks/anastasia-kladova/08-js-advanced-1/script.js
Solve all tasks except the 9th.
> [Homework #8] - JS Advanced 1 by Anastasia Kladava

- homeworks/anastasia-kladova/11-js-dom/index.html
- homeworks/anastasia-kladova/11-js-dom/script.js
- homeworks/anastasia-kladova/11-js-dom/style.css
Solve the task, implement basic and advanced functionality.
> [Homework #11] - JS-DOM by Anastasia Kladava

- homeworks/yuri-pantsialei/11-js-dom/index.html
- homeworks/yuri-pantsialei/11-js-dom/index.js
- homeworks/yuri-pantsialei/11-js-dom/styles.css
> [Homework #11] - JS-DOM by Yuri Pantelei

- homeworks/antonina-vechorko/09-js-advanced-2/index.js
@solvd-mmelnyk kindly check hometask, thank you
> [Homework #9] - JS Advanced 2 by Antonina Vechorko

- homeworks/antonina-vechorko/10-js-advanced-3/index.js
- homeworks/antonina-vechorko/10-js-advanced-3/task 5 /index.html
- homeworks/antonina-vechorko/10-js-advanced-3/task 5 /scripts/script1.js
- homeworks/antonina-vechorko/10-js-advanced-3/task 5 /scripts/script2.js
- homeworks/antonina-vechorko/10-js-advanced-3/task 5 /styles/styles.css
@solvd-mmelnyk kindly check this hometask. Thank you.
> [Homework #10] - JS Advanced 3 by Antonina Vechorko

- homeworks/antonina-vechorko/11-js-dom/index.html
- homeworks/antonina-vechorko/11-js-dom/script/index.js
- homeworks/antonina-vechorko/11-js-dom/styles/style.css
@solvd-mmelnyk kindly check, thank you
> [Homework #11] - JS Dom by Antonina Vechorko

- homeworks/maia-stulicfontan/12-data-structures-and-algorithms/result.log
- homeworks/maia-stulicfontan/12-data-structures-and-algorithms/scripts.js
> [Homework #12] - Data structures and algorithms by Maia Stulic Fontan

- homeworks/oleg-gorodenskyi/11-js-dom/index.html
- homeworks/oleg-gorodenskyi/11-js-dom/script.js
- homeworks/oleg-gorodenskyi/11-js-dom/style.css
> [Homework #11] - JS-DOM by Oleg Gorodenskyi

- homeworks/pavel-didenko/15-typescript/index.ts
- homeworks/pavel-didenko/15-typescript/tsconfig.json
> [Homework #15] - TypeScript by Pavel Didenko

- homeworks/oleg-gorodenskyi/15-typescript/script.ts
> [Homework #15] - TypeScript by Oleg Gorodenskyi

- homeworks/yuri-pantsialei/.gitignore
- homeworks/yuri-pantsialei/15-typescript/package-lock.json
- homeworks/yuri-pantsialei/15-typescript/package.json
- homeworks/yuri-pantsialei/15-typescript/src/index.html
- homeworks/yuri-pantsialei/15-typescript/src/index.ts
- homeworks/yuri-pantsialei/15-typescript/src/styles.scss
- homeworks/yuri-pantsialei/15-typescript/tsconfig.json
- homeworks/yuri-pantsialei/15-typescript/webpack.config.js
Create class basicCalculator and made  visual representation of calculator
> [Homework #15] - TypeScript by Yuri Pantelei

- homeworks/usmonbek-rustamov/08-js-advanced-1/script.js
Hey,
I comleted tasks in homework 8.
Please, have a look and let me know if it's all right
> [Homework #8] - JS Advanced 1 by Usmonbek Rustamov

- homeworks/maia-stulicfontan/15-typescript/scripts.ts
* Adds TS file for Homework 15
> [Homework #15] - Typescript by Maia Stulic Fontan

- homeworks/ilya-petrenko/ip-11-js-dom/index.html
- homeworks/ilya-petrenko/ip-11-js-dom/script.js
- homeworks/ilya-petrenko/ip-11-js-dom/styles.css
Created table with cells and implemented feature with Shift click.
> [Homework #11] - JS DOM by Ilya Petrenko

- homeworks/ilya-petrenko/ip-12-data-structures-and-algorithms/MOCK_DATA.js
- homeworks/ilya-petrenko/ip-12-data-structures-and-algorithms/result.log
- homeworks/ilya-petrenko/ip-12-data-structures-and-algorithms/script.js
Implemented both search algorithms. Results are written to a file.
> [Homework #12] Data structures and algorithms by Ilya Petrenko

- homeworks/usmonbek-rustamov/09-js-advanced-2/script.js
Hey,
I completed the homework. Please check my PR and let me know if everything is all right.
Thank you
> [Homework #9] - JS Advanced 2 by Usmonbek Rustamov

- homeworks/ilya-petrenko/ip-14-typescript/index.ts
- homeworks/ilya-petrenko/ip-14-typescript/tsconfig.json
Created 2 interfaces and one class.
>> tsc  ( to create dist directory which contains index.js file )
>> node dist/index.js
> [Homework #15] - TypeScript by Ilya Petrenko

- homeworks/usmonbek-rustamov/11-js-dom/index.html
- homeworks/usmonbek-rustamov/11-js-dom/script.js
- homeworks/usmonbek-rustamov/11-js-dom/style.css
> [Homework #11] - JS DOM by Usmonbek Rustamov

- homeworks/antonina-vechorko/15-typescript/index.ts
- yarn.lock
@solvd-mmelnyk, i hope now everything will be good
> [Homework #15] - Typescript by Antonina Vechorko

- homeworks/oleg-gorodenskyi/09-js-advanced-2/script.js
@ilya-ischenko kindly asking to check my hw. If it goes in a right way, I'll try to do rest part of the task.
>  [Homework #9] - JS Advanced 2 Oleg Gorodenskyi

- homeworks/pavel-didenko/17-react-basics/.gitignore
- homeworks/pavel-didenko/17-react-basics/index.html
- homeworks/pavel-didenko/17-react-basics/index.js
- homeworks/pavel-didenko/17-react-basics/styles/style.css
> [Homework #17] - React Basics by Pavel Didenko

- homeworks/antonina-vechorko/17-react-basics/index.html
- homeworks/antonina-vechorko/17-react-basics/index.jsx
- homeworks/antonina-vechorko/17-react-basics/style.css
@ilya-ischenko pls check hw-17, thank you.
> [Homework #17] - React Basics by Antonina Vechorko

- homeworks/yuri-pantsialei/17-react-basics/app.jsx
- homeworks/yuri-pantsialei/17-react-basics/index.html
- homeworks/yuri-pantsialei/17-react-basics/index.js
- homeworks/yuri-pantsialei/17-react-basics/styles.css
Please check my task and say is there something wrong, because I`m not confident that I done all correct :)
> [Homework #17] - React Basics by Yuri Pantelei

- homeworks/oleg-gorodenskyi/17-react-basics/index.html
- homeworks/oleg-gorodenskyi/17-react-basics/index.js
- homeworks/oleg-gorodenskyi/17-react-basics/style.css
@ilya-ischenko plz check my hw
> [Homework #17] - React Basics by Oleg Gorodenskyi

- README.md
There were no links to the task number 18 on the main page, I decided to make some contribution and add them by myself.
> Lecture 18, added links to the materials and to the task, in main readme file

- homeworks/maia-stulicfontan/17-react-basics/index.html
- homeworks/maia-stulicfontan/17-react-basics/index.jsx
- homeworks/maia-stulicfontan/17-react-basics/style.css
> [Homework #17] - React basics by Maia Stulic Fontan

- homeworks/usmonbek-rustamov/17-react-basics/index.html
- homeworks/usmonbek-rustamov/17-react-basics/index.jsx
- homeworks/usmonbek-rustamov/17-react-basics/style.css
> [Homework #17] - React basics by Usmonbek Rustamov

- homeworks/andrew-kondratiyk/20-react-api/.gitignore
- homeworks/andrew-kondratiyk/20-react-api/next.config.js
- homeworks/andrew-kondratiyk/20-react-api/package-lock.json
- homeworks/andrew-kondratiyk/20-react-api/package.json
- homeworks/andrew-kondratiyk/20-react-api/src/app/layout.tsx
- homeworks/andrew-kondratiyk/20-react-api/src/app/page.tsx
- homeworks/andrew-kondratiyk/20-react-api/src/components/common/add-todo-container/AddTodoContainer.tsx
- homeworks/andrew-kondratiyk/20-react-api/src/components/common/edit-todo-card/EditTodoCard.module.css
- homeworks/andrew-kondratiyk/20-react-api/src/components/common/edit-todo-card/EditTodoCard.tsx
- homeworks/andrew-kondratiyk/20-react-api/src/components/common/header/Header.module.css
- homeworks/andrew-kondratiyk/20-react-api/src/components/common/header/Header.tsx
- homeworks/andrew-kondratiyk/20-react-api/src/components/common/todo-card/TodoCard.module.css
- homeworks/andrew-kondratiyk/20-react-api/src/components/common/todo-card/TodoCard.tsx
- homeworks/andrew-kondratiyk/20-react-api/src/components/common/todo-list/TodoList.tsx
- homeworks/andrew-kondratiyk/20-react-api/src/components/pages/main-page/MainPage.module.css
- homeworks/andrew-kondratiyk/20-react-api/src/components/pages/main-page/MainPage.tsx
- homeworks/andrew-kondratiyk/20-react-api/src/context/TodoContext.ts
- homeworks/andrew-kondratiyk/20-react-api/src/hooks/useArray.js
- homeworks/andrew-kondratiyk/20-react-api/src/hooks/useAsync.js
- homeworks/andrew-kondratiyk/20-react-api/src/hooks/useEventListener.js
- homeworks/andrew-kondratiyk/20-react-api/src/hooks/useFetch.js
- homeworks/andrew-kondratiyk/20-react-api/src/hooks/useKeyPress.js
- homeworks/andrew-kondratiyk/20-react-api/src/hooks/useLocalStorage.ts
- homeworks/andrew-kondratiyk/20-react-api/src/hooks/useReducerLocalStorage.js
- homeworks/andrew-kondratiyk/20-react-api/src/styles/global.css
- homeworks/andrew-kondratiyk/20-react-api/src/types/todos.ts
- homeworks/andrew-kondratiyk/20-react-api/tsconfig.json
- yarn.lock
Hi, about hooks, I added to project which I already used and tried to research some new useful hooks. But honestly I didn't use any of them in project, bacause:
- I didn't find a place where I can use it, too small project.
- Almost all hooks I add in js and it's kinda hard to type it. So in project it's hard to use it, because you always get unknown types. But these hooks really useful, and it's really important to have right types on custom hooks, so one time I'll try to rewrite it to ts).
Also I avoided using useEffect ([that's why](https://react.dev/learn/you-might-not-need-an-effect)), so I get LS values inside reducer initializer and set set it in reducer function, I thought it's a good idea, so I want to know your opinion about that. But I have one problem, when next js try to do …
> [Homework #20] - React API by Andrew Kondratiyk

- homeworks/anastasia-kladova/17-react-basics/index.html
- homeworks/anastasia-kladova/17-react-basics/index.jsx
- homeworks/anastasia-kladova/17-react-basics/style.css
Implemented the traffic light.
> [Homework #17] - React Basics by Anastasia Kladova

- homeworks/svitlana-kovalenko/21-next-js-1/.gitignore
- homeworks/svitlana-kovalenko/21-next-js-1/src/components/Gallery/Gallery.tsx
> [Homework #21] - Next-js-1 by Svitlana Kovalenko
